name: Lint and build

on: push

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]
    
    steps:
    - uses: actions/checkout@v2
    - name: Check Lint
      uses: actions/setup-node@v2
      with: 
        node-version: '14'
    - run: npm install
    - run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions/setup-node@v2
      with: 
        node-version: '14'
    - run: npm install
    - run: npm run build